# Generated by Django 3.1 on 2021-07-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.CharField(choices=[('new', 'NEWEST'), ('old', 'OLDEST'), ('title', 'TITLE')], default='title', max_length=50),
        ),
    ]
