# Generated by Django 3.1 on 2021-07-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_auto_20210716_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.CharField(choices=[('new', 'NEWEST'), ('old', 'OLDEST'), ('title', 'TITLE')], default='old', max_length=50),
        ),
    ]
